version: "3.8"

services:
  localstack:
    image: localstack/localstack
    ports:
      - "127.0.0.1:4510-4559:4510-4559" # external service port range
      - "127.0.0.1:4566:4566" # LocalStack Edge Proxy
    expose:
      - "4566"
    environment:
      - DEBUG=${DEBUG-}
      - DATA_DIR=${DATA_DIR-}
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR-}
      - HOST_TMP_FOLDER=${TMPDIR:-/tmp/}localstack
      - DOCKER_HOST=unix:///var/run/docker.sock
    networks:
      - local
    volumes:
      - "${TMPDIR:-/tmp}/localstack:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - local

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
    depends_on:
      - mongo
    networks:
      - local

  backend:
    build: .
    image: api-localstack-s3
    volumes:
      - ./:/var/www/
    environment:
      S3_ENDPOINT_URL: http://host.docker.internal:4566
      S3_BUCKET_NAME: my-bucket
      MONGO_DB_HOSTNAME: mongo
      MONGO_DB_USERNAME: root
      MONGO_DB_PASSWORD: example
    expose:
      - "8080"
    ports:
      - "8080:8080"
    depends_on:
      - localstack
      - mongo
    links:
      - localstack
      - mongo
    networks:
      - local

networks:
  local:
    driver: bridge