spring:
  data:
    mongodb:
      host: ${MONGO_DB_HOSTNAME}
      port: 27017
      username: ${MONGO_DB_USERNAME}
      password: ${MONGO_DB_PASSWORD}
      database: images
      authentication-database: admin

  jackson:
    default-property-inclusion: non_null

aws:
  s3:
    endpoint-url: ${S3_ENDPOINT_URL}
    bucket-name: ${S3_BUCKET_NAME}
